from pathlib import Path

ROOT_DIR = Path()
DATA_DIR = ROOT_DIR / 'data'
DATA_SQL = ROOT_DIR / 'sql'

CUSTOMERS_TABLE_NAME = 'customers'
ORDER_ITEMS_TABLE_NAME = 'order_items'
ORDER_REVIEWS_TABLE_NAME = 'order_reviews'
ORDERS_TABLE_NAME = 'orders'
PAYMENTS_TABLE_NAME = 'payments'
PRODUCTS_TABLE_NAME = 'products'
SELLERS_TABLE_NAME = 'sellers'

TABLES_NAMES = [
    CUSTOMERS_TABLE_NAME,
    ORDER_ITEMS_TABLE_NAME,
    ORDER_REVIEWS_TABLE_NAME,
    ORDERS_TABLE_NAME,
    PAYMENTS_TABLE_NAME,
    PRODUCTS_TABLE_NAME,
    SELLERS_TABLE_NAME,
]
