DROP TABLE IF EXISTS geolocation;

CREATE TABLE geolocation (
zip_code_prefix SMALLINT PRIMARY KEY  NOT NULL,
latitude DECIMAL(9,6) NOT NULL,
longitude DECIMAL(9,6) NOT NULL,
city VARCHAR(32) NOT NULL,
state VARCHAR(2) NOT NULL);
